# Generated by Django 3.1 on 2020-08-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='upadate_desc',
            new_name='update_desc',
        ),
    ]
